services:
  uvx:
    build:
      context: ./uvx
    command: >
      uvx mcpo --port 8008 --config /config/config.json
    #WAS:  -- uvx mcp-server-time --local-timezone=America/Chicago
    ports:
      - "8008:8008"
    networks:
      - open-webui
    volumes:
      - ./mcpo-config:/config:ro
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - open-webui
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - open-webui    
    depends_on:
      - uvx

networks:
  open-webui:
    driver: bridge
volumes:
  ollama:
    name: ollama
    external: true
  open-webui:
    name: open-webui
    external: true
  


